CREATE TABLE CUSTOMERS (
    ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PHONE_NUMBERS (
    PHONE_NUMBER INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ACTIVATED BOOLEAN,
    DATE_ACTIVATED TIMESTAMP
);